const vids=['assets/venue1.mp4','assets/venue2.mp4','assets/venue3.mp4','assets/venue4.mp4','assets/venue5.mp4'];let i=0;
const v=document.getElementById('heroVideo'),dots=document.getElementById('dots');
vids.forEach((_,n)=>{const d=document.createElement('i');if(!n)d.className='active';d.onclick=()=>{i=n;play()};dots.appendChild(d)});
function play(){v.src=vids[i];v.play().catch(()=>{});[...dots.children].forEach((d,n)=>d.className=n===i?'active':'')}
v.onended=()=>{i=(i+1)%vids.length;play()};play();
const dateInput=document.getElementById('date');const status=document.createElement('div');status.id='availabilityStatus';status.setAttribute('aria-live','polite');dateInput?.insertAdjacentElement('afterend',status);
const API_BASE=(window.__TT_API_BASE__||'').replace(/\/$/,'');
async function api(url,options={}){const r=await fetch(API_BASE+url,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||'Request failed');return j}
async function checkDate(){if(!dateInput)return;const date=dateInput.value;if(!date){status.textContent='';return}try{const r=await api('/api/availability?date='+encodeURIComponent(date));status.textContent=r.available?'Proceed to book':'Day booked';status.className='availability '+(r.available?'available':'booked');dateInput.dataset.available=String(r.available)}catch{status.textContent='Unable to check date';status.className='availability booked'}}
dateInput?.addEventListener('change',checkDate);
function escapeText(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
document.getElementById('bookingForm').addEventListener('submit',async e=>{e.preventDefault();const x=id=>document.getElementById(id).value;await checkDate();if(dateInput.dataset.available!=='true'){alert('That day is already booked or unavailable.');return}const booking={name:x('name'),phone:x('phone'),type:x('type'),date:x('date'),guests:x('guests'),message:x('message')};try{await api('/api/bookings',{method:'POST',body:JSON.stringify(booking)});const text=`Hello Time & Tides Events!%0A%0AI would like to book the venue.%0AName: ${encodeURIComponent(booking.name)}%0APhone: ${encodeURIComponent(booking.phone)}%0AEvent: ${encodeURIComponent(booking.type)}%0ADate: ${encodeURIComponent(booking.date)}%0AGuests: ${encodeURIComponent(booking.guests||'Not specified')}%0AMessage: ${encodeURIComponent(booking.message||'None')}`;window.open('https://wa.me/2547310979723?text='+text,'_blank');alert('Booking request sent. Your request is pending admin confirmation.');e.target.reset();status.textContent=''}catch(err){alert(err.message)}});
let adminAuthenticated=false,adminBookings=[],adminInvoices=[];
function requireAdmin(){if(!adminAuthenticated){alert('Admin access required.');return false}return true}
const header=document.querySelector('header.top');const adminBtn=document.createElement('button');adminBtn.className='admin-link';adminBtn.textContent='Admin';adminBtn.onclick=openAdmin;header.appendChild(adminBtn);
async function loadAdminData(){const [b,inv]=await Promise.all([api('/api/bookings'),api('/api/invoices')]);adminBookings=b.bookings;adminInvoices=inv.invoices}
async function loadPublicSettings(){try{const r=await api('/api/settings');if(r.settings){document.querySelectorAll('[data-venue-name]').forEach(e=>e.textContent=r.settings.venueName);document.querySelectorAll('[data-venue-location]').forEach(e=>e.textContent=r.settings.location);document.querySelectorAll('[data-venue-phone]').forEach(e=>e.textContent=r.settings.phone);}}catch{}}
loadPublicSettings();
function openAdmin(){let panel=document.getElementById('adminPanel');if(panel){panel.classList.add('show');if(adminAuthenticated)renderAdmin();return}panel=document.createElement('section');panel.id='adminPanel';panel.className='admin-panel';panel.innerHTML=`<div class="admin-card"><button class="admin-close" onclick="closeAdmin()">×</button><p class="eyebrow">PRIVATE ADMIN AREA</p><h2>Manage Time & Tides</h2><div id="adminLogin"><p>Sign in with the secure admin password.</p><input id="adminPassword" type="password" autocomplete="current-password" placeholder="Admin password"><button class="btn primary" id="adminLoginBtn">Sign In</button><small>Your password is handled by the server and is not stored in the browser.</small></div><div id="adminContent" hidden><div class="admin-tabs"><button onclick="showAdminTab('bookings')">Bookings</button><button onclick="showAdminTab('dates')">Block Date</button><button onclick="showAdminTab('media')">Photos & Videos</button><button onclick="showAdminTab('edit')">Edit Details</button><button onclick="logoutAdmin()">Sign Out</button></div><div id="adminBody"></div></div></div>`;document.body.appendChild(panel);document.getElementById('adminLoginBtn').onclick=async()=>{try{await api('/api/login',{method:'POST',body:JSON.stringify({password:document.getElementById('adminPassword').value})});adminAuthenticated=true;document.getElementById('adminLogin').hidden=true;document.getElementById('adminContent').hidden=false;await loadAdminData();showAdminTab('bookings')}catch(err){alert(err.message)}}}
window.closeAdmin=()=>document.getElementById('adminPanel')?.classList.remove('show');
window.logoutAdmin=async()=>{await api('/api/logout',{method:'POST'});adminAuthenticated=false;document.getElementById('adminContent').hidden=true;document.getElementById('adminLogin').hidden=false;document.getElementById('adminPassword').value='';};
window.showAdminTab=async function(tab){if(!requireAdmin())return;const body=document.getElementById('adminBody');if(tab==='bookings'){await loadAdminData();body.innerHTML=`<h3>Booking requests</h3>${adminBookings.length?adminBookings.map(q=>`<div class="admin-item"><b>${escapeText(q.date)} — ${escapeText(q.type)}</b><p>${escapeText(q.name)} • ${escapeText(q.phone)} • ${escapeText(q.guests)} guests</p><span>Status: <strong>${escapeText(q.status)}</strong></span><div class="admin-actions">${q.status==='pending'?`<button onclick="confirmBooking('${q.id}')">Confirm & Notify</button>`:''}<button onclick="cancelBooking('${q.id}')">${q.status==='cancelled'?'Cancelled':'Cancel'}</button><button onclick="generateInvoice('${q.id}')">Invoice</button><button onclick="deleteBooking('${q.id}')">Delete</button></div></div>`).join(''):'<p>No booking requests yet.</p>'}`}
if(tab==='dates'){body.innerHTML=`<h3>Block a date</h3><p>Use this for days when the venue is unavailable.</p><input id="blockDate" type="date"><button class="btn primary" onclick="blockDate()">Block Date</button><div id="blockedDates"></div>`;renderBlockedDates()}
if(tab==='media'){body.innerHTML=`<h3>Add future photos & videos</h3><p>Prototype media is stored locally. Production should use secure cloud storage.</p><input id="mediaFiles" type="file" accept="image/*,video/*" multiple onchange="addMedia(event)"><div id="mediaList"></div>`;renderMedia()}
if(tab==='edit'){body.innerHTML=`<h3>Edit app details</h3><label>Venue name<input id="editVenue" value="${escapeText(localStorage.getItem('venueName')||'Time & Tides Events')}"></label><label>Location<input id="editLocation" value="${escapeText(localStorage.getItem('venueLocation')||'Punguvilla, Shelly Beach Road')}"></label><label>Phone<input id="editPhone" value="${escapeText(localStorage.getItem('venuePhone')||'07310979723')}"></label><button class="btn primary" onclick="saveDetails()">Save Changes</button>`}}
window.renderAdmin=()=>showAdminTab('bookings');
window.confirmBooking=async id=>{if(!requireAdmin())return;try{const r=await api('/api/bookings/'+id,{method:'PATCH',body:JSON.stringify({status:'confirmed'})});const q=r.booking;const msg=`Hello ${q.name}, your Time & Tides Events booking is confirmed for ${q.date}. Event: ${q.type}. Thank you!`;window.open('https://wa.me/'+q.phone.replace(/\D/g,'')+'?text='+encodeURIComponent(msg),'_blank');renderAdmin()}catch(e){alert(e.message)}};
window.cancelBooking=async id=>{if(!requireAdmin())return;try{await api('/api/bookings/'+id,{method:'PATCH',body:JSON.stringify({status:'cancelled'})});renderAdmin()}catch(e){alert(e.message)}};
window.deleteBooking=async id=>{if(!requireAdmin())return;try{await api('/api/bookings/'+id,{method:'DELETE'});renderAdmin()}catch(e){alert(e.message)}};
window.blockDate=async()=>{if(!requireAdmin())return;const d=document.getElementById('blockDate')?.value;if(!d)return alert('Choose a date.');try{await api('/api/blocked-dates',{method:'POST',body:JSON.stringify({date:d})});await renderBlockedDates();alert('Date blocked successfully.');}catch(e){alert(e.message)}};
window.renderBlockedDates=async()=>{const el=document.getElementById('blockedDates');if(!el)return;try{const r=await api('/api/blocked-dates');el.innerHTML=r.dates.length?'<h4>Blocked dates</h4>'+r.dates.map(d=>`<div class="admin-item"><b>${escapeText(d)}</b><button onclick="unblockDate('${d}')">Unblock</button></div>`).join(''):'<p>No blocked dates.</p>'}catch(e){el.innerHTML='<p>Unable to load blocked dates.</p>'}};
window.unblockDate=async d=>{if(!requireAdmin())return;try{await api('/api/blocked-dates/'+encodeURIComponent(d),{method:'DELETE'});renderBlockedDates()}catch(e){alert(e.message)}};
const MEDIA_KEY='timeTidesMedia';const getMedia=()=>JSON.parse(localStorage.getItem(MEDIA_KEY)||'[]');
window.addMedia=e=>{const existing=getMedia();[...e.target.files].forEach(f=>{if(f.size<4000000)existing.push({name:f.name,type:f.type,size:f.size,added:new Date().toISOString()});else alert(`${f.name} is larger than 4 MB.`)});localStorage.setItem(MEDIA_KEY,JSON.stringify(existing));renderMedia()};window.renderMedia=()=>{const el=document.getElementById('mediaList');if(!el)return;const m=getMedia();el.innerHTML=m.length?'<h4>Added media</h4>'+m.map((x,n)=>`<div class="admin-item"><b>${escapeText(x.name)}</b><button onclick="removeMedia(${n})">Remove</button></div>`).join(''):'<p>No extra media added yet.</p>'};window.removeMedia=n=>{const m=getMedia();m.splice(n,1);localStorage.setItem(MEDIA_KEY,JSON.stringify(m));renderMedia()};window.saveDetails=async()=>{if(!requireAdmin())return;try{await api('/api/settings',{method:'PATCH',body:JSON.stringify({venueName:document.getElementById('editVenue').value,location:document.getElementById('editLocation').value,phone:document.getElementById('editPhone').value})});alert('Changes saved securely on the server.')}catch(e){alert(e.message)}};
window.generateInvoice=async function(id){if(!requireAdmin())return;const b=adminBookings.find(x=>x.id===id);if(!b)return;const existing=adminInvoices.find(x=>x.bookingId===id);const amount=prompt('Enter invoice amount in KSh:',existing?.amount||'');if(amount===null)return;try{const r=await api('/api/invoices',{method:'POST',body:JSON.stringify({bookingId:id,amount:Number(amount)})});showInvoice(r.invoice,r.booking)}catch(e){alert(e.message)}};
function showInvoice(inv,b){if(!requireAdmin())return;let modal=document.getElementById('invoiceModal');if(!modal){modal=document.createElement('div');modal.id='invoiceModal';modal.className='invoice-modal';document.body.appendChild(modal)}modal.innerHTML=`<div class="invoice-card"><button class="admin-close" onclick="document.getElementById('invoiceModal').remove()">×</button><div id="invoicePrint"><p class="eyebrow">TIME & TIDES EVENTS</p><h2>INVOICE</h2><p><b>Invoice:</b> ${escapeText(inv.number)}<br><b>Issued:</b> ${new Date(inv.created).toLocaleDateString('en-KE')}<br><b>Payment due:</b> ${escapeText(inv.dueDate)}</p><hr><p><b>Customer:</b> ${escapeText(b.name)}<br><b>Phone:</b> ${escapeText(b.phone)}<br><b>Event:</b> ${escapeText(b.type)}<br><b>Venue date:</b> ${escapeText(b.date)}</p><h3>Total: KSh ${Number(inv.amount).toLocaleString('en-KE',{minimumFractionDigits:2})}</h3><div class="payment-box"><b>PAYMENT OPTIONS</b><p>💵 Cash — pay on site <b>5 days before</b> the booked date.</p><p>📱 Lipa na M-PESA — <b>Buy Goods & Services</b><br>Till Number: <b>6366527</b><br>Pay <b>5 days before</b> the booked date.</p></div></div><div class="invoice-actions"><button class="btn primary" onclick="printInvoice()">Print / Save PDF</button><button class="btn ghost dark" onclick="sendInvoiceWhatsApp('${inv.id}','${b.id}')">Send Invoice by WhatsApp</button></div></div>`}
window.printInvoice=()=>{if(!requireAdmin())return;const content=document.getElementById('invoicePrint')?.innerHTML;if(!content)return;const w=window.open('','_blank');w.document.write(`<html><head><title>Time & Tides Invoice</title><style>body{font-family:Arial,sans-serif;padding:30px;color:#123}h2{margin-bottom:4px}.payment-box{border:1px solid #ccc;padding:15px;margin-top:20px}</style></head><body>${content}</body></html>`);w.document.close();w.print()};
window.sendInvoiceWhatsApp=async(invId,bookingId)=>{if(!requireAdmin())return;const inv=adminInvoices.find(x=>x.id===invId),b=adminBookings.find(x=>x.id===bookingId);if(!inv||!b)return;const msg=`Hello ${b.name},%0A%0ATime & Tides Events Invoice ${encodeURIComponent(inv.number)}%0AEvent: ${encodeURIComponent(b.type)}%0AVenue date: ${encodeURIComponent(b.date)}%0ATotal: KSh ${encodeURIComponent(inv.amount)}%0APayment due: ${encodeURIComponent(inv.dueDate)}%0A%0APayment options:%0A1. Cash — pay on site 5 days before the booked date.%0A2. Lipa na M-PESA — Buy Goods & Services — Till Number: 6366527 — pay 5 days before the booked date.%0A%0AThank you, Time & Tides Events.`;window.open('https://wa.me/'+b.phone.replace(/\D/g,'')+'?text='+msg,'_blank')};