const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');const {Pool}=require('pg');
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,DB=process.env.DATABASE_URL,ADMIN=process.env.ADMIN_PASSWORD||'change-me',SALT=process.env.PASSWORD_SALT||'time-tides-change-this';
const pool=DB?new Pool({connectionString:DB,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}):null;let dbReady=false;
const demo={bookings:[],invoices:[],blocked:[],settings:{venueName:'Time & Tides Events',location:'Punguvilla, Shelly Beach Road',phone:'0731099723'},sessions:{}};
const dataFile=path.join(ROOT,'server-data','data.json');function loadDemo(){try{return JSON.parse(fs.readFileSync(dataFile,'utf8'))}catch{return JSON.parse(JSON.stringify(demo))}}function saveDemo(d){fs.mkdirSync(path.dirname(dataFile),{recursive:true});fs.writeFileSync(dataFile,JSON.stringify(d,null,2))}
function hash(s){return crypto.createHash('sha256').update(s).digest('hex')}function passwordHash(s){return crypto.scryptSync(s,SALT,32).toString('hex')}function token(){return crypto.randomBytes(32).toString('hex')}
async function initDb(){if(!pool)return false;await pool.query(`CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS bookings(id UUID PRIMARY KEY,name TEXT NOT NULL,phone TEXT NOT NULL,type TEXT NOT NULL,event_date DATE NOT NULL,guests TEXT,message TEXT,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ NOT NULL DEFAULT now());CREATE TABLE IF NOT EXISTS invoices(id UUID PRIMARY KEY,booking_id UUID UNIQUE NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,number TEXT UNIQUE NOT NULL,amount NUMERIC(12,2) NOT NULL,due_date DATE NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());CREATE TABLE IF NOT EXISTS blocked_dates(event_date DATE PRIMARY KEY);CREATE TABLE IF NOT EXISTS admin_sessions(token_hash TEXT PRIMARY KEY,expires_at TIMESTAMPTZ NOT NULL);`);await pool.query(`INSERT INTO settings(key,value) VALUES ('venueName','Time & Tides Events'),('location','Punguvilla, Shelly Beach Road'),('phone','0731099723') ON CONFLICT(key) DO NOTHING`);return true}
function json(res,status,obj){const body=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN','Referrer-Policy':'strict-origin-when-cross-origin'});res.end(body)}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1000000)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});req.on('error',reject)})}
function cookie(req){const m=(req.headers.cookie||'').match(/tt_admin=([^;]+)/);return m?m[1]:null}async function authed(req){const t=cookie(req);if(!t)return false;if(pool&&dbReady){const r=await pool.query('SELECT 1 FROM admin_sessions WHERE token_hash=$1 AND expires_at>now()', [hash(t)]);return r.rowCount>0}const d=loadDemo();return !!(d.sessions[hash(t)]&&new Date(d.sessions[hash(t)])>new Date())}
async function api(req,res,u){if(req.method==='GET'&&u.pathname==='/health')return json(res,200,{ok:true});
 if(req.method==='POST'&&u.pathname==='/api/login'){const b=await body(req);if(typeof b.password!=='string'||!crypto.timingSafeEqual(Buffer.from(passwordHash(b.password)),Buffer.from(passwordHash(ADMIN))))return json(res,401,{error:'Invalid password'});const t=token(),exp=new Date(Date.now()+8*60*60*1000);if(pool&&dbReady)await pool.query('INSERT INTO admin_sessions(token_hash,expires_at) VALUES($1,$2)',[hash(t),exp]);else{const d=loadDemo();d.sessions[hash(t)]=exp.toISOString();saveDemo(d)}res.setHeader('Set-Cookie',`tt_admin=${t}; HttpOnly; SameSite=Strict; Path=/; ${process.env.NODE_ENV==='production'?'Secure; ':''}Max-Age=28800`);return json(res,200,{ok:true})}
 if(req.method==='POST'&&u.pathname==='/api/logout'){const t=cookie(req);if(t&&pool&&dbReady)await pool.query('DELETE FROM admin_sessions WHERE token_hash=$1',[hash(t)]);if(t&&!pool){const d=loadDemo();delete d.sessions[hash(t)];saveDemo(d)}res.setHeader('Set-Cookie','tt_admin=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,200,{ok:true})}
 if(req.method==='GET'&&u.pathname==='/api/settings'){if(pool&&dbReady){const r=await pool.query('SELECT key,value FROM settings');return json(res,200,{settings:Object.fromEntries(r.rows.map(x=>[x.key,x.value]))})}return json(res,200,{settings:loadDemo().settings})}
 if(req.method==='PATCH'&&u.pathname==='/api/settings'){if(!(await authed(req)))return json(res,401,{error:'Admin access required'});const b=await body(req),allowed=['venueName','location','phone'];if(pool&&dbReady){for(const k of allowed)if(b[k]!=null)await pool.query('INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=excluded.value',[k,String(b[k]).slice(0,200)]);const r=await pool.query('SELECT key,value FROM settings');return json(res,200,{settings:Object.fromEntries(r.rows.map(x=>[x.key,x.value]))})}const d=loadDemo();for(const k of allowed)if(b[k]!=null)d.settings[k]=String(b[k]).slice(0,200);saveDemo(d);return json(res,200,{settings:d.settings})}
 if(req.method==='GET'&&u.pathname==='/api/availability'){const d=u.searchParams.get('date');if(!/^\d{4}-\d{2}-\d{2}$/.test(d))return json(res,400,{error:'Valid date required'});let taken=false;if(pool&&dbReady){const r=await pool.query(`SELECT 1 FROM blocked_dates WHERE event_date=$1 UNION SELECT 1 FROM bookings WHERE event_date=$1 AND status<>'cancelled' LIMIT 1`,[d]);taken=r.rowCount>0}else{const x=loadDemo();taken=x.blocked.includes(d)||x.bookings.some(b=>b.date===d&&b.status!=='cancelled')}return json(res,200,{available:!taken,date:d})}
 if(req.method==='POST'&&u.pathname==='/api/bookings'){const b=await body(req);if(!b.name||!b.phone||!b.type||!/^\d{4}-\d{2}-\d{2}$/.test(b.date))return json(res,400,{error:'Name, phone, event type and valid date are required'});let available=true;if(pool&&dbReady){const r=await pool.query(`SELECT 1 FROM blocked_dates WHERE event_date=$1 UNION SELECT 1 FROM bookings WHERE event_date=$1 AND status<>'cancelled' LIMIT 1`,[b.date]);available=r.rowCount===0;if(available){const r2=await pool.query(`INSERT INTO bookings(id,name,phone,type,event_date,guests,message) VALUES(gen_random_uuid(),$1,$2,$3,$4,$5,$6) RETURNING *`,[String(b.name).slice(0,160),String(b.phone).slice(0,40),String(b.type).slice(0,80),b.date,String(b.guests||'').slice(0,40),String(b.message||'').slice(0,2000)]);const q=r2.rows[0];return json(res,201,{booking:{id:q.id,name:q.name,phone:q.phone,type:q.type,date:q.event_date.toISOString().slice(0,10),guests:q.guests,message:q.message,status:q.status}})}}else{const x=loadDemo();available=!(x.blocked.includes(b.date)||x.bookings.some(q=>q.date===b.date&&q.status!=='cancelled'));if(available){const q={id:crypto.randomUUID(),name:String(b.name).slice(0,160),phone:String(b.phone).slice(0,40),type:String(b.type).slice(0,80),date:b.date,guests:String(b.guests||'').slice(0,40),message:String(b.message||'').slice(0,2000),status:'pending',created:new Date().toISOString()};x.bookings.push(q);saveDemo(x);return json(res,201,{booking:q})}}return json(res,409,{error:'That date is already booked or unavailable'})}
 if(u.pathname==='/api/bookings'&&!['GET'].includes(req.method)){};
 if(req.method==='GET'&&u.pathname==='/api/bookings'){if(!(await authed(req)))return json(res,401,{error:'Admin access required'});if(pool&&dbReady){const r=await pool.query('SELECT id,name,phone,type,event_date,guests,message,status,created_at FROM bookings ORDER BY event_date,created_at');return json(res,200,{bookings:r.rows.map(q=>({...q,date:q.event_date.toISOString().slice(0,10),created:q.created_at}))})}return json(res,200,{bookings:loadDemo().bookings})}
 const bm=u.pathname.match(/^\/api\/bookings\/([^/]+)$/);if(bm&&req.method==='PATCH'){if(!(await authed(req)))return json(res,401,{error:'Admin access required'});const b=await body(req);if(!['confirmed','cancelled','pending'].includes(b.status))return json(res,400,{error:'Invalid status'});if(pool&&dbReady){const r=await pool.query('UPDATE bookings SET status=$1 WHERE id=$2 RETURNING *',[b.status,bm[1]]);if(!r.rowCount)return json(res,404,{error:'Booking not found'});const q=r.rows[0];return json(res,200,{booking:{id:q.id,name:q.name,phone:q.phone,type:q.type,date:q.event_date.toISOString().slice(0,10),guests:q.guests,message:q.message,status:q.status}})}const d=loadDemo(),q=d.bookings.find(x=>x.id===bm[1]);if(!q)return json(res,404,{error:'Booking not found'});q.status=b.status;saveDemo(d);return json(res,200,{booking:q})}
 if(bm&&req.method==='DELETE'){if(!(await authed(req)))return json(res,401,{error:'Admin access required'});if(pool&&dbReady){await pool.query('DELETE FROM bookings WHERE id=$1',[bm[1]])}else{const d=loadDemo();d.bookings=d.bookings.filter(q=>q.id!==bm[1]);saveDemo(d)}return json(res,200,{ok:true})}
 if(req.method==='GET'&&u.pathname==='/api/blocked-dates'){if(!(await authed(req)))return json(res,401,{error:'Admin access required'});if(pool&&dbReady){const r=await pool.query('SELECT event_date FROM blocked_dates ORDER BY event_date');return json(res,200,{dates:r.rows.map(x=>x.event_date.toISOString().slice(0,10))})}return json(res,200,{dates:loadDemo().blocked})}
 if(req.method==='POST'&&u.pathname==='/api/blocked-dates'){if(!(await authed(req)))return json(res,401,{error:'Admin access required'});const b=await body(req);if(!/^\d{4}-\d{2}-\d{2}$/.test(b.date))return json(res,400,{error:'Valid date required'});if(pool&&dbReady)await pool.query('INSERT INTO blocked_dates(event_date) VALUES($1) ON CONFLICT DO NOTHING',[b.date]);else{const d=loadDemo();if(!d.blocked.includes(b.date))d.blocked.push(b.date);saveDemo(d)}return json(res,201,{ok:true})}
 const bd=u.pathname.match(/^\/api\/blocked-dates\/([^/]+)$/);if(bd&&req.method==='DELETE'){if(!(await authed(req)))return json(res,401,{error:'Admin access required'});const d=decodeURIComponent(bd[1]);if(pool&&dbReady)await pool.query('DELETE FROM blocked_dates WHERE event_date=$1',[d]);else{const x=loadDemo();x.blocked=x.blocked.filter(q=>q!==d);saveDemo(x)}return json(res,200,{ok:true})}
 if(req.method==='GET'&&u.pathname==='/api/invoices'){if(!(await authed(req)))return json(res,401,{error:'Admin access required'});if(pool&&dbReady){const r=await pool.query('SELECT id,booking_id,number,amount,due_date,created_at FROM invoices ORDER BY created_at DESC');return json(res,200,{invoices:r.rows.map(x=>({id:x.id,bookingId:x.booking_id,number:x.number,amount:x.amount,dueDate:x.due_date.toISOString().slice(0,10),created:x.created_at}))})}return json(res,200,{invoices:loadDemo().invoices})}
 if(req.method==='POST'&&u.pathname==='/api/invoices'){if(!(await authed(req)))return json(res,401,{error:'Admin access required'});const b=await body(req),amount=Number(b.amount);if(!b.bookingId||!Number.isFinite(amount)||amount<0)return json(res,400,{error:'Booking and valid amount required'});const due=new Date();due.setDate(due.getDate()+5);const dueDate=due.toISOString().slice(0,10);if(pool&&dbReady){const br=await pool.query('SELECT * FROM bookings WHERE id=$1',[b.bookingId]);if(!br.rowCount)return json(res,404,{error:'Booking not found'});const n='TT-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-5);const r=await pool.query('INSERT INTO invoices(id,booking_id,number,amount,due_date) VALUES(gen_random_uuid(),$1,$2,$3,$4) ON CONFLICT(booking_id) DO UPDATE SET amount=excluded.amount RETURNING *',[b.bookingId,n,amount,dueDate]);const x=r.rows[0],q=br.rows[0];return json(res,201,{invoice:{id:x.id,bookingId:x.booking_id,number:x.number,amount:x.amount,dueDate:x.due_date.toISOString().slice(0,10),created:x.created_at},booking:{id:q.id,name:q.name,phone:q.phone,type:q.type,date:q.event_date.toISOString().slice(0,10)}})}const d=loadDemo(),q=d.bookings.find(x=>x.id===b.bookingId);if(!q)return json(res,404,{error:'Booking not found'});let x=d.invoices.find(z=>z.bookingId===b.bookingId);if(!x){x={id:crypto.randomUUID(),bookingId:q.id,number:'TT-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-5),amount,dueDate,created:new Date().toISOString()};d.invoices.push(x)}else{x.amount=amount}saveDemo(d);return json(res,201,{invoice:x,booking:q})}
 return false}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/')||u.pathname==='/health'){const r=await api(req,res,u);if(r!==false)return}let p=decodeURIComponent(u.pathname);if(p==='/')p='/index.html';const file=path.normalize(path.join(ROOT,p));if(!file.startsWith(ROOT))return json(res,403,{error:'Forbidden'});fs.stat(file,(e,s)=>{if(e||!s.isFile()){res.writeHead(404);return res.end('Not found')}const ext=path.extname(file),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.webmanifest':'application/manifest+json','.mp4':'video/mp4','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN','Referrer-Policy':'strict-origin-when-cross-origin'});fs.createReadStream(file).pipe(res)})}catch(e){console.error(e);if(!res.headersSent)json(res,500,{error:'Server error'})}});
initDb().then(ok=>{dbReady=ok;server.listen(PORT,()=>console.log(`Time & Tides Events running on ${PORT}`))}).catch(e=>{console.error(e);server.listen(PORT,()=>console.log(`Time & Tides Events running on ${PORT} without DB`))});